version: '3.9'

services:

  django-postgres:
    container_name: django-postgres
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${DJANGO_DATABASE_USER}
      - POSTGRES_PASSWORD=${DJANGO_DATABASE_PASSWORD}
      - POSTGRES_DB=${DJANGO_DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data           

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app 
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
  django_data: