# Generated by Django 4.2.6 on 2024-03-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("contact_person", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Robot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100)),
                ("production_date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("four_wheel", "Four Wheel"),
                            ("amphibia", "Amphibia"),
                            ("tracked", "Tracked"),
                            ("flying", "Flying"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "communication_device",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="robot",
                        to="communication.communicationdevice",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robots",
                        to="companies.company",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robots",
                        to="robots.manufacturer",
                    ),
                ),
            ],
        ),
    ]
