# Generated by Django 4.2.6 on 2024-03-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("industry", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("contact_person", models.CharField(max_length=100)),
                ("krs", models.CharField(max_length=100)),
            ],
        ),
    ]
